@extends('layouts.app')

@section('title', 'Roles y permisos | CPIMuni')
@section('page-title', 'Roles y permisos')

@section('content')
@include('partials.form-feedback')
<div class="admin-forms"><section class="card"><div class="card-title">Crear rol</div><form method="POST" action="{{ route('admin.roles.store') }}" class="compact-form">@csrf<input name="nombre" required placeholder="Nombre del rol"><input name="descripcion" placeholder="Descripción"><button class="button" type="submit">Crear rol</button></form></section><section class="card"><div class="card-title">Crear permiso</div><form method="POST" action="{{ route('admin.permisos.store') }}" class="compact-form">@csrf<input name="nombre" required placeholder="ej. reportes.exportar"><input name="modulo" placeholder="Módulo"><input name="descripcion" placeholder="Descripción"><button class="button" type="submit">Crear permiso</button></form></section></div>
<div class="roles-list">@foreach($roles as $rol)<section class="card role-card"><div class="role-header"><div><h3>{{ $rol->nombre }}</h3><p>{{ $rol->descripcion ?: 'Sin descripción' }} · {{ $rol->usuarios_count }} usuarios</p></div>@if($rol->nombre !== 'SUPERADMIN' && $rol->usuarios_count === 0)<form method="POST" action="{{ route('admin.roles.destroy', $rol) }}" onsubmit="return confirm('¿Eliminar este rol?')">@csrf @method('DELETE')<button class="icon-button danger" title="Eliminar rol"><i class="fa-solid fa-trash"></i></button></form>@endif</div><form method="POST" action="{{ route('admin.roles.update', $rol) }}">@csrf @method('PUT')<input type="hidden" name="descripcion" value="{{ $rol->descripcion }}"><div class="permissions">@foreach($permisos as $permiso)<label><input type="checkbox" name="permisos[]" value="{{ $permiso->id }}" @checked($rol->permisos->contains($permiso->id))> {{ $permiso->nombre }}</label>@endforeach</div><button class="button" type="submit">Guardar permisos</button></form></section>@endforeach</div>
<section class="card permissions-card"><div class="card-title">Catálogo de permisos</div><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Módulo</th><th>Descripción</th><th>Acciones</th></tr></thead><tbody>@foreach($permisos as $permiso)<tr><form method="POST" action="{{ route('admin.permisos.update', $permiso) }}">@csrf @method('PUT')<td><input name="nombre" value="{{ $permiso->nombre }}" required></td><td><input name="modulo" value="{{ $permiso->modulo }}"></td><td><input name="descripcion" value="{{ $permiso->descripcion }}"></td><td class="actions"><button class="icon-button" title="Guardar" type="submit"><i class="fa-solid fa-floppy-disk"></i></button></form>@if($permiso->roles()->count() === 0)<form method="POST" action="{{ route('admin.permisos.destroy', $permiso) }}" onsubmit="return confirm('¿Eliminar este permiso?')">@csrf @method('DELETE')<button class="icon-button danger" title="Eliminar" type="submit"><i class="fa-solid fa-trash"></i></button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
@endsection

@push('styles')<style>
.admin-forms{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.compact-form{display:grid;grid-template-columns:1fr 1fr;gap:9px}.compact-form input:last-of-type{grid-column:span 2}.roles-list{display:grid;gap:16px}.role-header{display:flex;justify-content:space-between;align-items:start}.role-card h3{font-size:16px;margin-bottom:4px}.role-card p{font-size:12px;color:#64748b;margin-bottom:17px}.permissions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:16px 0;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0}.permissions label{font-size:11px;color:#475569}.permissions input{accent-color:#2563eb}.button{margin-top:16px;border:0;border-radius:8px;padding:10px 14px;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.icon-button{border:0;background:#eff6ff;color:#2563eb;border-radius:7px;padding:7px 9px;cursor:pointer}.icon-button.danger{background:#fee2e2;color:#b91c1c}.actions{display:flex;gap:6px;align-items:center}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid #e2e8f0}th{font-size:10px;text-transform:uppercase;color:#64748b}td input{width:100%;padding:7px;border:1px solid #cbd5e1;border-radius:6px}.alert{padding:10px 12px;border-radius:8px;margin-bottom:14px;font-size:12px}.alert.success{background:#dcfce7;color:#166534}.alert.error{background:#fee2e2;color:#991b1b}@media(max-width:900px){.admin-forms{grid-template-columns:1fr}.permissions{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>@endpush
