@extends('layouts.app')

@section('title', 'Organización | CPIMuni')
@section('page-title', 'Estructura organizacional')

@section('content')
@include('partials.form-feedback')
<div class="org-grid">
<a id="organigrama"></a>
<section class="card"><div class="card-title">Órganos</div><form method="POST" action="{{ route('organizacion.organos.store') }}" class="inline-form">@csrf @include('organizacion.partials.municipalidad')<input name="codigo" placeholder="Código"><input name="nombre" required placeholder="Nombre"><input name="tipo" placeholder="Tipo"><button class="button" type="submit"><i class="fa-solid fa-plus"></i></button></form><div class="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Tipo</th><th>Acciones</th></tr></thead><tbody>@forelse($organos as $organo)<tr><td>{{ $organo->codigo ?: '—' }}</td><td>{{ $organo->nombre }}</td><td>{{ $organo->tipo ?: '—' }}</td><td class="actions"><a class="icon-button" title="Editar" href="{{ route('organizacion.edit', ['organos', $organo->id]) }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('organizacion.destroy', ['organos', $organo->id]) }}" onsubmit="return confirm('¿Dar de baja este órgano?')">@csrf @method('DELETE')<button class="icon-button danger" title="Dar de baja" type="submit"><i class="fa-solid fa-ban"></i></button></form></td></tr>@empty<tr><td colspan="4" class="empty">Sin órganos registrados.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><div class="card-title">Unidades orgánicas</div><form method="POST" action="{{ route('organizacion.unidades.store') }}" class="stack-form">@csrf @include('organizacion.partials.municipalidad')<select name="organo_id"><option value="">Sin órgano</option>@foreach($organos as $organo)<option value="{{ $organo->id }}">{{ $organo->nombre }}</option>@endforeach</select><input name="codigo" placeholder="Código"><input name="nombre" required placeholder="Nombre"><textarea name="finalidad" placeholder="Finalidad"></textarea><button class="button" type="submit">Registrar unidad</button></form><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Órgano</th><th>Acciones</th></tr></thead><tbody>@forelse($unidades as $unidad)<tr><td>{{ $unidad->nombre }}<small>{{ $unidad->codigo }}</small></td><td>{{ $unidad->organo?->nombre ?: '—' }}</td><td class="actions"><a class="icon-button" title="Editar" href="{{ route('organizacion.edit', ['unidades', $unidad->id]) }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('organizacion.destroy', ['unidades', $unidad->id]) }}">@csrf @method('DELETE')<button class="icon-button danger" title="Dar de baja" type="submit"><i class="fa-solid fa-ban"></i></button></form></td></tr>@empty<tr><td colspan="3" class="empty">Sin unidades registradas.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><div class="card-title">Puestos</div><form method="POST" action="{{ route('organizacion.puestos.store') }}" class="inline-form">@csrf @include('organizacion.partials.municipalidad')<select name="unidad_organica_id"><option value="">Sin unidad</option>@foreach($unidades as $unidad)<option value="{{ $unidad->id }}">{{ $unidad->nombre }}</option>@endforeach</select><input name="codigo" placeholder="Código"><input name="denominacion" required placeholder="Denominación"><button class="button" type="submit"><i class="fa-solid fa-plus"></i></button></form><div class="table-wrap"><table><thead><tr><th>Puesto</th><th>Unidad</th><th>Acciones</th></tr></thead><tbody>@forelse($puestos as $puesto)<tr><td>{{ $puesto->denominacion }}<small>{{ $puesto->codigo }}</small></td><td>{{ $puesto->unidad?->nombre ?: '—' }}</td><td class="actions"><a class="icon-button" title="Editar" href="{{ route('organizacion.edit', ['puestos', $puesto->id]) }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('organizacion.destroy', ['puestos', $puesto->id]) }}">@csrf @method('DELETE')<button class="icon-button danger" title="Dar de baja" type="submit"><i class="fa-solid fa-ban"></i></button></form></td></tr>@empty<tr><td colspan="3" class="empty">Sin puestos registrados.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><div class="card-title">Funciones</div><form method="POST" action="{{ route('organizacion.funciones.store') }}" class="stack-form">@csrf @include('organizacion.partials.municipalidad')<div class="form-row"><input name="codigo" placeholder="Código"><input name="tipo" placeholder="Tipo"></div><select name="unidad_organica_id"><option value="">Sin unidad</option>@foreach($unidades as $unidad)<option value="{{ $unidad->id }}">{{ $unidad->nombre }}</option>@endforeach</select><textarea name="descripcion" required placeholder="Descripción de la función"></textarea><button class="button" type="submit">Registrar función</button></form><div class="table-wrap"><table><thead><tr><th>Código</th><th>Descripción</th><th>Unidad</th><th>Acciones</th></tr></thead><tbody>@forelse($funciones as $funcion)<tr><td>{{ $funcion->codigo ?: '—' }}</td><td>{{ $funcion->descripcion }}</td><td>{{ $funcion->unidad?->nombre ?: '—' }}</td><td class="actions"><a class="icon-button" title="Editar" href="{{ route('organizacion.edit', ['funciones', $funcion->id]) }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('organizacion.destroy', ['funciones', $funcion->id]) }}">@csrf @method('DELETE')<button class="icon-button danger" title="Dar de baja" type="submit"><i class="fa-solid fa-ban"></i></button></form></td></tr>@empty<tr><td colspan="4" class="empty">Sin funciones registradas.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection

@push('styles')<style>
.org-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.card-title{display:flex;justify-content:space-between}.inline-form,.stack-form{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.stack-form{display:grid}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}input,select,textarea{min-width:0;padding:9px 10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit;font-size:12px}textarea{min-height:62px;resize:vertical}.inline-form input,.inline-form select{flex:1}.button{border:0;border-radius:8px;padding:9px 12px;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #e2e8f0}th{font-size:10px;text-transform:uppercase;color:#64748b}td small{display:block;color:#64748b;margin-top:3px}.actions{display:flex;gap:5px;align-items:center}.icon-button{border:0;background:#eff6ff;color:#2563eb;border-radius:7px;padding:6px 8px;cursor:pointer;text-decoration:none}.icon-button.danger{background:#fee2e2;color:#b91c1c}.empty{text-align:center;color:#64748b;padding:20px}.alert{padding:10px 12px;border-radius:8px;margin-bottom:14px;font-size:12px}.alert.success{background:#dcfce7;color:#166534}.alert.error{background:#fee2e2;color:#991b1b}@media(max-width:950px){.org-grid{grid-template-columns:1fr}}
</style>
@endpush
