@extends('layouts.app')

@section('title', 'Normativa | CPIMuni')
@section('page-title', 'Normativa')

@section('content')
@include('partials.form-feedback')
<div class="page-grid"><section class="card"><div class="card-title">Registrar norma</div><form method="POST" action="{{ route('normativa.store') }}" class="form-grid">@csrf<label>Tipo<input name="tipo" required placeholder="Ordenanza, resolución..."></label><label>Número<input name="numero"></label><label class="wide">Título<input name="titulo" required></label><label>Fecha de emisión<input type="date" name="fecha_emision"></label><label>Fecha de vigencia<input type="date" name="fecha_vigencia"></label><label class="wide">Enlace<input type="url" name="enlace" placeholder="https://..."></label><label class="wide">Resumen<textarea name="resumen"></textarea></label><div><button class="button" type="submit"><i class="fa-solid fa-plus"></i> Registrar norma</button></div></form></section><section class="card"><div class="card-title">Normas registradas</div><div class="table-wrap"><table><thead><tr><th>Norma</th><th>Fechas</th><th>Municipalidad</th><th>Estado</th></tr></thead><tbody>@forelse($normas as $norma)<tr><td><strong>{{ $norma->tipo }} {{ $norma->numero }}</strong><small>{{ $norma->titulo }}</small></td><td>{{ $norma->fecha_emision?->format('d/m/Y') ?: '—' }}<small>Vigencia: {{ $norma->fecha_vigencia?->format('d/m/Y') ?: '—' }}</small></td><td>{{ $norma->municipalidad?->nombre ?: 'Global' }}</td><td><span class="status active">{{ $norma->estado }}</span></td></tr>@empty<tr><td colspan="4" class="empty">No hay normas registradas.</td></tr>@endforelse</tbody></table></div>{{ $normas->links() }}</section></div>
@endsection

@push('styles')<style>
.page-grid{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(500px,1.6fr);gap:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{font-size:11px;font-weight:700;color:#475569}.wide{grid-column:span 2}input,textarea{display:block;width:100%;margin-top:6px;padding:10px 11px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit;font-size:13px}textarea{min-height:80px}.button{margin-top:20px;border:0;border-radius:8px;padding:11px 15px;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:13px 10px;border-bottom:1px solid #e2e8f0;white-space:nowrap}th{font-size:10px;text-transform:uppercase;color:#64748b}td small{display:block;color:#64748b;margin-top:3px}.status{padding:4px 8px;border-radius:999px;font-size:10px;font-weight:700}.active{background:#dcfce7;color:#166534}.empty{padding:28px;text-align:center;color:#64748b}.alert{padding:10px 12px;border-radius:8px;margin-bottom:14px;font-size:12px}.alert.success{background:#dcfce7;color:#166534}.alert.error{background:#fee2e2;color:#991b1b}@media(max-width:900px){.page-grid{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}}
</style>
@endpush
